"""
TaskGraph DAG Model
Generated by ChatGPT
==================

Lightweight dependency model for task pipelines where each task produces output files.

Principles
----------
- The DAG is the source of truth for task state.
- The filesystem is only checked for a task's own outputs.
- Dependency validity is handled by in-memory propagation (no recursive rescans).
- Assumes users do not manually modify the working directory.

States
------
LOCKED       : Dependencies not satisfied.
READY        : Can run (deps done, outputs missing).
DONE         : Outputs exist and deps satisfied.

Usage
-----
- Create Task(id, outputs, deps)
- Build graph = TaskGraph(tasks)
- On task finish: graph.mark_finished(id)
- On rerun:      graph.rerun(id)

Signals
-------
- task_changed(task_id)
- graph_changed()

Notes
-----
- Cycles are not supported.
- Add full rescans or timestamps if external file edits must be handled.
"""

from collections import defaultdict
from dataclasses import dataclass
from enum import Enum
from pathlib import Path

from PySide6.QtCore import QObject, Signal

from src.model.FileManager import FileManager

from .abstract_task_graph import AbstractTaskGraph, GraphLayout, TaskState


class TasksToIds(Enum):
    TRACK_POSES = "track_poses"
    TRACK_FENCERS = "track_fencers"
    GENERATE_HEAT_MAP = "generate_heat_map"
    CROP_REGIONS = "Identify Scoreboard, Timer and Piste"
    PERFORM_OCR = "Extract Scoring"
    DETECT_SCORE_LIGHTS = "Detect Score Lights"
    GENERATE_MOMENTUM_GRAPH = "Generate Momentum Graph"
    SELECT_PERIODS = "Select Periods"
    VIEW_STATS = "View Stats"


class MomentumGraphTasksToIds(Enum):
    CROP_REGIONS = TasksToIds.CROP_REGIONS.value
    PERFORM_OCR = TasksToIds.PERFORM_OCR.value
    DETECT_SCORE_LIGHTS = TasksToIds.DETECT_SCORE_LIGHTS.value
    GENERATE_MOMENTUM_GRAPH = TasksToIds.GENERATE_MOMENTUM_GRAPH.value
    SELECT_PERIODS = TasksToIds.SELECT_PERIODS.value
    VIEW_STATS = TasksToIds.VIEW_STATS.value


class HeatMapTasksToIds(Enum):
    TRACK_POSES = TasksToIds.TRACK_POSES.value
    TRACK_FENCERS = TasksToIds.TRACK_FENCERS.value
    GENERATE_HEAT_MAP = TasksToIds.GENERATE_HEAT_MAP.value
    CROP_REGIONS = TasksToIds.CROP_REGIONS.value
    PERFORM_OCR = TasksToIds.PERFORM_OCR.value
    DETECT_SCORE_LIGHTS = TasksToIds.DETECT_SCORE_LIGHTS.value
    GENERATE_MOMENTUM_GRAPH = TasksToIds.GENERATE_MOMENTUM_GRAPH.value


@dataclass
class GraphNode:
    id: str
    state: TaskState
    deps: list[str]
    children: list[str]


class Task:
    def __init__(self, tid: str, outputs: list[str], deps: list[str] | None = None):
        self.id = tid
        self.outputs = [Path(p) for p in outputs]
        self.deps = deps or []
        self.children: list[str] = []
        self.state = TaskState.LOCKED


class TaskGraph(AbstractTaskGraph):
    task_changed = Signal(str)
    graph_changed = Signal()

    def __init__(
        self,
        tasks: list[Task],
        file_manager: FileManager,
        parent=None,
    ):
        super().__init__(parent)

        self.tasks: dict[str, Task] = {t.id: t for t in tasks}
        self.file_manager = file_manager
        self.working_dir: Path | None = None

        for t in tasks:
            for dep in t.deps:
                self.tasks[dep].children.append(t.id)

    # ===============================
    # Public API (unchanged)
    # ===============================

    def state(self, tid: str) -> TaskState:
        return self.tasks[tid].state

    def rerun(self, tid: str):
        self.invalidate_downstream(tid)
        self.tasks[tid].state = TaskState.READY
        self.recompute_children(tid)
        self.graph_changed.emit()

    def mark_finished(self, tid: str):
        self.update_single_task(tid)
        self.recompute_children(tid)
        self.graph_changed.emit()

    def set_working_directory(self, working_dir: str):
        self.working_dir = Path(working_dir)
        self.initial_scan()
        self.graph_changed.emit()

    def get_task_states(self) -> dict[str, str]:
        return {tid: task.state.name for tid, task in self.tasks.items()}

    def get_index_map(self) -> dict[str, int]:
        topo = self.topological_order()
        return {tid: i + 1 for i, tid in enumerate(topo)}

    def snapshot(self) -> GraphLayout:
        layers = self._topological_layers()
        edges = [(t.id, c) for t in self.tasks.values() for c in t.children]
        return GraphLayout(layers, edges)

    # ===============================
    # Exposed Core Methods
    # ===============================

    def initial_scan(self):
        for tid in self.tasks:
            self.update_single_task(tid)

        for tid in self.tasks:
            self.recompute_children(tid)

    def update_single_task(self, tid: str):
        task = self.tasks[tid]

        if not self.deps_done(task):
            task.state = TaskState.LOCKED
            return

        if self.outputs_exist(task):
            task.state = TaskState.DONE
        else:
            task.state = TaskState.READY

        self.task_changed.emit(tid)

    def recompute_children(self, tid: str):
        for child_id in self.tasks[tid].children:
            child = self.tasks[child_id]
            old = child.state
            self.update_single_task(child_id)
            if child.state != old:
                self.recompute_children(child_id)

    def invalidate_downstream(self, tid: str):
        for child_id in self.tasks[tid].children:
            child = self.tasks[child_id]
            if child.state in (TaskState.DONE, TaskState.READY):
                child.state = TaskState.LOCKED
                self.task_changed.emit(child_id)
                self.invalidate_downstream(child_id)

    # ===============================
    # Helpers
    # ===============================

    def outputs_exist(self, task: Task) -> bool:
        if not self.file_manager:
            return False
        return all(self.file_manager.file_exists(p) for p in task.outputs)

    def deps_done(self, task: Task) -> bool:
        return all(self.tasks[d].state == TaskState.DONE for d in task.deps)

    def _on_match_changed(self):
        self.initial_scan()
        self.graph_changed.emit()

    def _topological_layers(self):
        depth: dict[str, int] = {}

        def compute_depth(tid: str) -> int:
            if tid in depth:
                return depth[tid]
            if not self.tasks[tid].deps:
                depth[tid] = 0
            else:
                depth[tid] = 1 + max(compute_depth(d) for d in self.tasks[tid].deps)
            return depth[tid]

        for tid in self.tasks:
            compute_depth(tid)

        layers = defaultdict(list)
        for tid, d in depth.items():
            layers[d].append(tid)

        return [layers[i] for i in sorted(layers)]

    def topological_order(self):
        visited = set()
        order = []

        def dfs(tid: str):
            if tid in visited:
                return
            visited.add(tid)
            for child in self.tasks[tid].children:
                dfs(child)
            order.append(tid)

        for tid in self.tasks:
            dfs(tid)

        return list(reversed(order))
